SET EXPANDER=C:\Program Files\7-Zip\7z.exe
SET DESKTOP=%USERPROFILE%\Desktop
SET INFILE=%DESKTOP%\WinUpdate2018-12-12.msu
SET TARGETDIR=%TEMP%\WinUpdate20181212
IF NOT EXIST "%TARGETDIR%" MKDIR "%TARGETDIR%"

"%EXPANDER%" x "%INFILE%" -bt -bb3 -o"%TARGETDIR%"
CD "%TARGETDIR%"
IF NOT EXIST WSUSSCAN MKDIR WSUSSCAN
EXPAND.EXE "WSUSSCAN.cab" "WSUSSCAN"
EXPAND.EXE "WSUSSCAN\WSUSSCAN.cab" -F:* "WSUSSCAN"
DEL "WSUSSCAN\WSUSSCAN.cab"
DEL "WSUSSCAN.cab"
IF NOT EXIST PSFX MKDIR PSFX
EXPAND.EXE "*_PSFX.cab" -F:* "PSFX"
"%EXPANDER%" x *_PSFX.cab -bt -bb3 -oPSFX _manifest_.cix.xml
DEL "*_PSFX.cab"